### PR TITLE
Add processor for rapidyaml

### PR DESCRIPTION
**Pull request by biojppm**
Hi!

First, let me start by expressing a very loud and heartfelt THANK YOU to the people involved in this project. It has helped me enormously getting my own project to a better state, and it gave me precious guidance when moving through the many dark places in YAML.

This is a draft PR for adding [rapidyaml](https://github.com/biojppm/rapidyaml) to the test suite. Please do not merge yet; this is meant to get early feedback. I did not try to build or run yet, and it is possible that further changes upstream are required to make this work.

### CODE REVIEW

**Comment by ingydotnet** [comment]
@biojppm Thank you for doing this for us. It will help us get rapidyaml into our various testing systems.

At the moment when I try to build I'm getting:
```
[ 87%] Building CXX object tools/CMakeFiles/ryml-yaml-events.dir/yaml_events.cpp.o
/build/foo/tools/yaml_events.cpp:4:10: fatal error: c4/fs/fs.hpp: No such file or directory
    4 | #include <c4/fs/fs.hpp>
      |          ^~~~~~~~~~~~~~
compilation terminated.
```
It seems to be something new you've added to https://github.com/biojppm/c4core repo but maybe not pushed?
I can't seem to find anything about `fs` in there.

**Comment by biojppm** [comment]
c4fs is cloned by cmake when building. How are you building the project?

**Comment by ingydotnet** [comment]
In an alpine:latest container with basics installed:
```
bash-5.1# git clone --recursive https://github.com/biojppm/rapidyaml.git
Cloning into 'rapidyaml'...
remote: Enumerating objects: 8031, done.
remote: Counting objects: 100% (994/994), done.
remote: Compressing objects: 100% (323/323), done.
remote: Total 8031 (delta 721), reused 823 (delta 636), pack-reused 7037
Receiving objects: 100% (8031/8031), 2.29 MiB | 8.53 MiB/s, done.
Resolving deltas: 100% (5065/5065), done.
Submodule 'extern/c4core' (https://github.com/biojppm/c4core) registered for path 'ext/c4core'
Cloning into '/rapidyaml/ext/c4core'...
remote: Enumerating objects: 3943, done.        
remote: Counting objects: 100% (1429/1429), done.        
remote: Compressing objects: 100% (684/684), done.        
remote: Total 3943 (delta 865), reused 1092 (delta 590), pack-reused 2514        
Receiving objects: 100% (3943/3943), 1.14 MiB | 4.67 MiB/s, done.
Resolving deltas: 100% (2464/2464), done.
Submodule path 'ext/c4core': checked out '0a5d475c9946da68c26b1fe1689daa720d5ca15a'
Submodule 'cmake' (https://github.com/biojppm/cmake) registered for path 'ext/c4core/cmake'
Submodule 'extern/debugbreak' (https://github.com/biojppm/debugbreak) registered for path 'ext/c4core/src/c4/ext/debugbreak'
Submodule 'src/c4/ext/fast_float' (https://github.com/fastfloat/fast_float) registered for path 'ext/c4core/src/c4/ext/fast_float'
Cloning into '/rapidyaml/ext/c4core/cmake'...
remote: Enumerating objects: 884, done.        
remote: Counting objects: 100% (275/275), done.        
remote: Compressing objects: 100% (179/179), done.        
remote: Total 884 (delta 165), reused 195 (delta 89), pack-reused 609        
Receiving objects: 100% (884/884), 1002.35 KiB | 4.40 MiB/s, done.
Resolving deltas: 100% (537/537), done.
Cloning into '/rapidyaml/ext/c4core/src/c4/ext/debugbreak'...
remote: Enumerating objects: 183, done.        
remote: Counting objects: 100% (13/13), done.        
remote: Compressing objects: 100% (11/11), done.        
remote: Total 183 (delta 6), reused 7 (delta 2), pack-reused 170        
Receiving objects: 100% (183/183), 42.33 KiB | 24.00 KiB/s, done.
Resolving deltas: 100% (99/99), done.
Cloning into '/rapidyaml/ext/c4core/src/c4/ext/fast_float'...
remote: Enumerating objects: 1532, done.        
remote: Counting objects: 100% (531/531), done.        
remote: Compressing objects: 100% (236/236), done.        
remote: Total 1532 (delta 292), reused 426 (delta 236), pack-reused 1001        
Receiving objects: 100% (1532/1532), 457.61 KiB | 2.90 MiB/s, done.
Resolving deltas: 100% (928/928), done.
Submodule path 'ext/c4core/cmake': checked out '9416f297430bc358eea48f8cf65aa0d602029629'
Submodule path 'ext/c4core/src/c4/ext/debugbreak': checked out '5dcbe41d2bd4712c8014aa7e843723ad7b40fd74'
Submodule path 'ext/c4core/src/c4/ext/fast_float': checked out '32d21dcecb404514f94fb58660b8029a4673c2c1'
bash-5.1# cd rapidyaml/
bash-5.1# cmake -S .  -B build -DBUILD_SHARED_LIBS=OFF -DRYML_BUILD_TOOLS=ON
-- The CXX compiler identification is GNU 10.3.1
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- ryml: using C++ standard: C++11
-- ryml: setting C++ standard: 11
-- ryml: setting C++ standard required: ON
-- ryml: importing subproject c4core (SUBDIRECTORY)... /rapidyaml/ext/c4core
-- c4core: using C++ standard: C++11
-- ryml: -----> target ryml PUBLIC incorporating lib c4core
-- ryml: packing the project: 
-- ryml: cpack tag: v0.3.0-56-gf07a432-master
-- Configuring done
-- Generating done
-- Build files have been written to: /rapidyaml/build
bash-5.1# cmake --build build -j --target ryml-yaml-events
[  6%] Building CXX object CMakeFiles/ryml.dir/src/c4/yml/common.cpp.o
[ 12%] Building CXX object CMakeFiles/ryml.dir/src/c4/yml/node.cpp.o
[ 18%] Building CXX object CMakeFiles/ryml.dir/src/c4/yml/preprocess.cpp.o
[ 25%] Building CXX object CMakeFiles/ryml.dir/src/c4/yml/parse.cpp.o
[ 31%] Building CXX object CMakeFiles/ryml.dir/src/c4/yml/tree.cpp.o
[ 43%] Building CXX object CMakeFiles/ryml.dir/ext/c4core/src/c4/char_traits.cpp.o[ 43%] Building CXX object CMakeFiles/ryml.dir/ext/c4core/src/c4/error.cpp.o

[ 50%] Building CXX object CMakeFiles/ryml.dir/ext/c4core/src/c4/language.cpp.o
[ 56%] Building CXX object CMakeFiles/ryml.dir/ext/c4core/src/c4/format.cpp.o
[ 62%] Building CXX object CMakeFiles/ryml.dir/ext/c4core/src/c4/base64.cpp.o
[ 68%] Building CXX object CMakeFiles/ryml.dir/ext/c4core/src/c4/memory_resource.cpp.o
[ 75%] Building CXX object CMakeFiles/ryml.dir/ext/c4core/src/c4/memory_util.cpp.o
[ 81%] Linking CXX static library libryml.a
[ 81%] Built target ryml
[ 87%] Building CXX object tools/CMakeFiles/ryml-yaml-events.dir/__/test/test_suite/test_suite_events_emitter.cpp.o
[ 93%] Building CXX object tools/CMakeFiles/ryml-yaml-events.dir/yaml_events.cpp.o
/rapidyaml/tools/yaml_events.cpp:4:10: fatal error: c4/fs/fs.hpp: No such file or directory
    4 | #include <c4/fs/fs.hpp>
      |          ^~~~~~~~~~~~~~
compilation terminated.
make[3]: *** [tools/CMakeFiles/ryml-yaml-events.dir/build.make:76: tools/CMakeFiles/ryml-yaml-events.dir/yaml_events.cpp.o] Error 1
make[3]: *** Waiting for unfinished jobs....
make[2]: *** [CMakeFiles/Makefile2:226: tools/CMakeFiles/ryml-yaml-events.dir/all] Error 2
make[1]: *** [CMakeFiles/Makefile2:233: tools/CMakeFiles/ryml-yaml-events.dir/rule] Error 2
make: *** [Makefile:241: ryml-yaml-events] Error 2
bash-5.1# 
```

**Comment by ingydotnet** [comment]
I see. c4fs is separate from c4core. Missed that.
Seems it's not in `CMakeLists.txt`.
I can try adding it.
New to cmake...

**Comment by perlpunk** [comment]
I pushed to your branch to add `cpp-rapidyaml` to the Makefile.
So you can just do `make cpp-rapidyaml`.
Hope that was ok.

**Comment by ingydotnet** [comment]
I do see it now in `tools/CMakeLists.txt`.
But after running the build commands, `find . | fgrep c4fs` finds nothing.
I'll keep trying.

**Comment by perlpunk** [comment]
What I needed to do to run `make ryml` successfully was:
```
cp -r src/c4 build/;
cp src/*.hpp build/
```
But still `make ryml-yaml-events` complains about not finding `c4/fs/fs.hpp`

@biojppm you can just try out your PR doing `make cpp-rapidyaml`.

**Comment by ingydotnet** [comment]
Tried adding it as submodule:

```
# cat .gitmodules 
[submodule "extern/c4core"]
	path = ext/c4core
	url = https://github.com/biojppm/c4core
[submodule "extern/c4fs"]
	path = extern/c4fs
	url = https://github.com/biojppm/c4fs
```
but that didn't help :\

**Comment by ingydotnet** [comment]
Got it to build after adding submodule and tweaking CMakeLists.txt
```
# git status && git diff
On branch master
Your branch is up to date with 'origin/master'.

Changes to be committed:
  (use "git restore --staged <file>..." to unstage)
	modified:   .gitmodules
	new file:   ext/c4fs

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
	modified:   CMakeLists.txt

diff --git a/CMakeLists.txt b/CMakeLists.txt
index b22579a..dda612e 100644
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -19,7 +19,12 @@ option(RYML_DBG "Enable (very verbose) ryml debug prints." OFF)
 #-------------------------------------------------------
 
 c4_require_subproject(c4core INCORPORATE
-    SUBDIRECTORY ${RYML_EXT_DIR}/c4core)
+    SUBDIRECTORY ${RYML_EXT_DIR}/c4core
+    )
+
+c4_require_subproject(c4fs INCORPORATE
+    SUBDIRECTORY ${RYML_EXT_DIR}/c4fs
+    )
 
 c4_add_library(ryml
     SOURCES
```

Run
```
# echo 'foo: bar' | ./build/tools/ryml-yaml-events -
+STR
+DOC
+MAP
=VAL :foo
=VAL :bar
-MAP
-DOC
-STR
```

**Comment by ingydotnet** [comment]
Here's the commit that added it to our other runtimes repo:
https://github.com/yaml/yaml-test-runtimes/commit/ea0ef26be0da54b7493e0cd22943db1c92e78324

Rapid YAML is now present in https://play.yaml.io/main/parser
commit: https://github.com/yaml/yaml-play/commit/a3101ac55bbfe058cb6357c875381863fab82cf1

Ran this against the test suite for events. 
https://docs.google.com/spreadsheets/d/e/2PACX-1vSlIvGsUqrCvf4s9PhVJeAyvvlx0rOfZFgox4ZexwCYpPH0gdkQN36o0AJaDageHbLp-FgY538FLO5c/pubhtml?gid=0&single=true

It's failing 283 of 402 but I think mostly due to minor formatting issues. I'll make issues on the rapidyaml repo.

@perlpunk can likely work this into https://matrix.yaml.info/ soon.

Thanks again, @biojppm 

Stop by https://matrix.to/#/#chat:yaml.io sometime, and say Hi.

**Comment by biojppm** [comment]
Hi @ingydotnet - thanks for all the hard work, and apologies for not getting back sooner. The failure with c4fs is my own fault, from a setting that was not correctly propagated by -DRYML_BUILD_TOOLS=ON (which I added yesterday; when I tried on my PC, my working dir was tainted with the correct setting and it appeared to work). I will fix it upstream.

**Comment by biojppm** [comment]
@ingydotnet The commit above fixes the problem. The current master should be good to go, but I will get to try it on my own.

**Comment by ingydotnet** [comment]
Thanks. That was awfully simple. Wish you'd been around while I was fumbling to get it working. :)
At least I learned a little bit.

Fixed yaml-test-runtimes with https://github.com/yaml/yaml-test-runtimes/commit/2176cc254c18d40580983b47999da742e63a2608

**Comment by biojppm** [comment]
Thanks, that was my bad. Sorry again for not being able to reply timely.

I guess that this particular PR is ready? Feel free to un-draft it if you think it is appropriate. 

Also, see yaml/yaml-play#1 and yaml/yaml-test-runtimes#2 .

**Comment by perlpunk** [comment]
Ok, I pushed two fixes to the branch. `make testv LIBRARY=cpp-rapidyaml` is now passing.

I noticed that you always output `...` when there was a `---`

So the only thing that would be good is to have it building from a tar archive instead of git master.
But we can also do that later. I can try to get it into the matrix now.

**Comment by biojppm** [comment]
@perlpunk @ingydotnet I guess the PR is ready. Once I make the next release (in the coming days) I will add a PR with the proper version; for now, let's stick with master.

**Pull request merged**
