### PR TITLE
Refactor Java build

### PR DESCRIPTION
**Pull request by asomov**
- Fix minor typos
- Use Maven wrapper
- implement event dumping

### CODE REVIEW

**Comment by asomov** [comment]
The YAML feature added, now Java is complete:    ` tests: [event, json, yaml]`

```
$ docker run -i --rm yamlio/alpine-runtime-java java-snakeyaml-yaml <t/data/input.yaml
%TAG ! !
%TAG !! tag:yaml.org,2002:
---
foo: bar
```

**Comment by perlpunk** [comment]
I got a small test failure.
I wanted to push to your branch, but I don't have permission.
So I pushed to `PR/23` on origin: https://github.com/yaml/yaml-runtimes/commit/c4091573ae482ee535bc97efbe588d54f9cc35f1

Can you check?
Also it would be nice if by default no tag directives were printed. Then we could remove the extra test file under `t/data/`.

**Comment by asomov** [comment]
@perlpunk No tag directives are printed. It showed some minor issue which I may fix later in SnakeYAML

**Comment by perlpunk** [comment]
Thanks, merged! Happy new year!

**Comment by asomov** [comment]
Thank you.
Happy New Year !

**Pull request merged**
